--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.9) ~  Much Love, Ferib 

]]--

local v0=129954712878723;local v1=game:GetService("Players");local v2=game:GetService("ReplicatedStorage");local v3=game:GetService("TeleportService");local v4=game:GetService("HttpService");local v5=v1.LocalPlayer;math.randomseed(tick());local v6=v2:WaitForChild("GameEvents"):WaitForChild("TradeWorld"):WaitForChild("TravelToTradeWorld");local v7=v2:WaitForChild("GameEvents"):WaitForChild("TradeEvents"):WaitForChild("Booths"):WaitForChild("ClaimBooth");local v8={Ochil_28=true,setokmimic=true,CihuyyXuhuyyy11=true};local function v9() for v20,v21 in ipairs(v1:GetPlayers()) do if (v21.Name~=v5.Name) then if v8[v21.Name] then return v21.Name;end end end return nil;end local function v10() local v14=game.PlaceId;v3.TeleportInitFailed:Connect(function(v22,v23,v24) warn("Teleport FAILED:",v23,v24);end);while true do warn("SEARCHING SERVER >20 PLAYERS...");local v25,v26=pcall(function() return v4:JSONDecode(game:HttpGet("https://games.roblox.com/v1/games/"   .. v14   .. "/servers/Public?sortOrder=Desc&limit=100" ));end);local v27={};if (v25 and v26 and v26.data) then for v40,v41 in ipairs(v26.data) do if ((v41.playing>20) and (v41.playing<v41.maxPlayers) and (v41.id~=game.JobId)) then table.insert(v27,v41);end end end if ( #v27>0) then table.sort(v27,function(v42,v43) return v42.playing>v43.playing ;end);local v38=v27[math.random(1,math.min( #v27,5))];local v39=pcall(function() v3:TeleportToPlaceInstance(v14,v38.id,v5);end);if v39 then warn("Teleport attempted → waiting result...");task.wait(5);else warn("Teleport call failed → retrying...");end else warn("No valid server found → retry in 3s");end task.wait(3);end end local function v11(v15) for v28,v29 in ipairs(v15:GetDescendants()) do if v29:IsA("SurfaceGui") then for v44,v45 in ipairs(v29:GetDescendants()) do if v45:IsA("TextLabel") then local v46=v45.Text;if (v46 and (v46~="")) then local v47=v46:lower();if (v47:find("claim") or v47:find("rent") or v47:find("empty") or v47:find("buy") or v47:find("open")) then continue;end if (( #v46>=3) and ( #v46<=20)) then return v46;end end end end end end return "Unclaimed";end local function v12(v16,v17) local v18=0;while v18<v17  do local v30=v11(v16);if (v30~="Unclaimed") then return true;end task.wait(0.5);v18+=0.5 end return false;end local function v13() local v19=workspace:WaitForChild("TradeWorld"):WaitForChild("Booths");for v31,v32 in ipairs(v19:GetChildren()) do local v33=v32:GetPivot().Position.Y;local v34=v11(v32);if ((v33<1) and (v34=="Unclaimed")) then return v32;end end return nil;end if (game.PlaceId~=v0) then v6:FireServer();print("Teleporting to Trade World...");else task.wait(3);local v35=v9();if v35 then warn("Blacklisted player detected:",v35);v10();return;end local v36=v13();if  not v36 then warn("No empty booth → hopping server");v10();return;end print("Trying to claim:",v36.Name);v7:FireServer(v36);local v37=v12(v36,5);if v37 then print("SUCCESS: Booth claimed");else warn("FAILED: claim gagal → hopping server");v10();end end
